### ISSUE TITLE
signif_column was useful!

### ISSUE THREAD

**Issue by jzadra** [IndrajeetPatil/ipmisc#15]
Hi,

I have been using signif_column to produce tables in lots of my code (typically after using `broom::tidy()`.  Any chance we could get it back?  If not I'll just grab the code and add it to my personal package.

**Comment by IndrajeetPatil** [comment]
Oops, sorry about that. 

Feel free to use this code in your package:

```r
#' @noRd
#'
#' @importFrom tibble tibble as_tibble

# function body
signif_column <- function(data, p, ...) {
  # add new significance column based on standard APA guidelines
  dplyr::mutate(
    .data = data,
    significance = dplyr::case_when(
      {{ p }} >= 0.050 ~ "ns",
      {{ p }} < 0.050 & {{ p }} >= 0.010 ~ "*",
      {{ p }} < 0.010 & {{ p }} >= 0.001 ~ "**",
      {{ p }} < 0.001 ~ "***"
    )
  ) %>% # convert to tibble dataframe
    tibble::as_tibble(.)
}
```

**Comment by IndrajeetPatil** [comment]
I retired the function because in `ggstatsplot`, I no longer use asterisk-based conventions to convey _p_-values. These conventions seem natural and intuitive to psychologists, but were really confusing to anyone else who was using the package.

**Comment by jzadra** [comment]
Thanks, I've added it to my personal package!
